version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/base:stable

orbs:
  node: circleci/node@4.7.0
      
jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages

workflows:
  my-custom-workflow:
    jobs:
      - install
      - node/run:
          npm-run: all


          