version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-s3: circleci/aws-s3@3.0.0

parameters:
  app-id:
    type: string
    default: "bio"

jobs:
  build:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run: 
          name: "Configure project"
          command: mv ~/project/data/config.json.default ~/project/data/config.json
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run ci
      - run: 
          name: Compress artefact
          command: cd dist; zip -r ../dist.zip *
      - aws-s3/copy:  
          from: dist.zip
          to: s3://artifacts-jmrlab/<< pipeline.parameters.app-id >>/bio_dist_{{ .Branch }}.zip
      - persist_to_workspace:
          root: ~/project/
          paths:
            - dist.zip

  deploy_dev:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: ~/project/
      - run: 
          name: Deploy to DEV
          command: "curl -u $AUTH_TOKEN -f -X 'POST' \"https://$NODEPAD_HOST/api/apps/<< pipeline.parameters.app-id >>-dev/content/zip\" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'bin=@dist.zip;type=application/zip'"      
  
  deploy_prod:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: ~/project/
      - run: 
          name: Depoy to PROD
          command: "curl -u $AUTH_TOKEN -f -X 'POST' \"https://$NODEPAD_HOST/api/apps/<< pipeline.parameters.app-id >>/content/zip\" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'bin=@dist.zip;type=application/zip'"      

workflows:
  cicd-workflow:
    jobs:
      - build:
          context:
            - nodepad.jmrlab.com
      - deploy_dev:
          requires:
            - build
          context:
            - nodepad.jmrlab.com
          filters:
              branches:
                only:
                  - develop
      - deploy_prod:
          requires:
            - build
          context:
            - nodepad.jmrlab.com
          filters:
              branches:
                only:
                  - master