version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  ci-all:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run: npm run all
      
workflows:
  build-workflow:
    jobs:
      - ci-all