version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  install:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm --version
      - run: mv ~/project/data/config.json.default ~/project/data/config.json
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: npm run all
      - run: cd dist; zip -r ../jamro_net_dist.zip *
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: "curl -u $AUTH_TOKEN -f -X 'POST' 'https://nodepad-api.jmrlab.com/api/apps/bio-dev/content/zip' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'bin=@jamro_net_dist.zip;type=application/zip'"      

      
workflows:
  dev-workflow:
    jobs:
      - install
      - build
          requires:
            - install
      - deploy
          requires:
            - build
