version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  ci-all:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run: node --version
      - run: npm --version
      - run: mv ~/project/data/config.json.default ~/project/data/config.json
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run all
      - run: zip -r ~/project/jamro_net_dist.zip ~/project/dist
      - run: "curl -X 'POST' 'https://nodepad-api.jmrlab.com/api/apps/bio-dev/content/zip' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -H \"authorization: Basic $AUTH_TOKEN\" -F 'bin=@jamro_net_dist.zip;type=application/zip'"      

      
workflows:
  build-workflow:
    jobs:
      - ci-all
