---
name: NodeJS with Webpack
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create config.json file
        run: "echo '{ \"config\": { \"ga\": \"${{ secrets.GA_CODE }}\" } }' > ./data/config.json"
      - name: Build
        run: |
          npm install
          npm run build
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: public_html/
